return {
	"catgoose/nvim-colorizer.lua",
	event = { "BufReadPost", "BufNewFile" },
	opts = {
		filetypes = { "*" },
		buftypes = {},
		user_commands = true,
		lazy_load = false,
		user_default_options = {
			names = true,
			names_opts = {
				lowercase = true,
				camelcase = true,
				uppercase = false,
				strip_digits = true,
			},
			names_custom = false,
			RGB = true,
			RGBA = true,
			RRGGBB = true,
			RRGGBBAA = false,
			AARRGGBB = false,
			rgb_fn = true,
			hsl_fn = true,
			css = true,
			css_fn = true,
			tailwind = "normal",
			tailwind_opts = {
				update_names = false,
			},
			sass = {
				enable = true,
				parsers = { "css" },
			},
			mode = "background",
			virtualtext = "■",
			virtualtext_inline = false,
			virtualtext_mode = "foreground",
			always_update = false,
			hooks = {
				disable_line_highlight = false,
			},
		},
	},
}
